[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "RAG"
version = "0.0.1"
description = "Task Specialized RAG for Financial Analysis"
authors = [{ name = "Daniel", email = "daniel.liu@stern.nyu.edu"}]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib"
]
pythonpath = "src"
testpaths=["tests"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
filterwarnings = [
    "ignore::DeprecationWarning:bs4.builder._lxml"
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]